export interface Product {
  id: number;
  category: string;
  categoryType: string;
  styles: string[];
  tastes: string[];
  title: string;
  description: string;
  detailDescription: string;
  includes: string[];
  tags: string[];
  price: string;
  image?: string;
  styleTag?: string;
  moodTag?: string;
  locationTag?: string;
  instagramUrl?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    category: '🍽️ 장소',
    categoryType: '장소',
    styles: ['로맨틱', '우아한'],
    tastes: ['와인&샴페인', '라이브 음악'],
    title: '한강 뷰 프라이빗 다이닝',
    description: '한강 야경이 내려다보이는 프라이빗 룸에서 둘만의 로맨틱 디너',
    detailDescription:
      '서울 최고의 전망을 자랑하는 프라이빗 다이닝 룸입니다. 한강과 도시 야경이 펼쳐지는 창가 테이블에서 셰프가 직접 준비하는 7코스 디너와 프리미엄 와인 페어링을 즐기실 수 있습니다. 디저트와 함께 특별한 순간을 연출해 드립니다.',
    includes: ['7코스 맞춤 메뉴', '와인 페어링', '전담 플로리스트', '현악 3중주', '포토그래퍼'],
    tags: ['한강뷰', '프라이빗', '코스요리'],
    price: '80만원~',
    styleTag: '코스요리',
    moodTag: '로맨틱',
    locationTag: '한강뷰',
    instagramUrl: 'https://www.instagram.com/wedu_official',
  },
  {
    id: 2,
    category: '🏨 장소',
    categoryType: '장소',
    styles: ['우아한', '럭셔리'],
    tastes: ['와인&샴페인', '럭셔리 패키지'],
    title: '5성급 호텔 스위트 프로포즈',
    description: '최고급 스위트룸에서 샴페인과 함께하는 품격 있는 프러포즈',
    detailDescription:
      '5성급 호텔의 최고급 스위트룸에서 진행되는 프리미엄 프로포즈 패키지입니다. 샴페인과 룸 데코레이션, 케이크가 포함되며 품격 있는 순간을 선사합니다.',
    includes: ['스위트룸 1박', '샴페인 & 케이크', '룸 데코레이션', '조식 서비스'],
    tags: ['럭셔리', '스위트룸', '호캉스'],
    price: '150만원~',
    styleTag: '스위트룸',
    moodTag: '럭셔리',
    locationTag: '5성급 호텔',
    instagramUrl: 'https://www.instagram.com/wedu_hotel_suite',
  },
  {
    id: 3,
    category: '🌅 장소',
    categoryType: '장소',
    styles: ['모험적', '감성적'],
    tastes: ['자연 속에서', '사진 촬영'],
    title: '제주도 해변 선셋 프로포즈',
    description: '제주도의 황홀한 석양을 배경으로 펼치는 감동의 순간',
    detailDescription:
      '제주도의 아름다운 해변에서 석양을 배경으로 진행되는 프로포즈입니다. 해변 세팅과 사진 촬영이 포함되어 잊지 못할 순간을 남겨드립니다.',
    includes: ['해변 세팅', '석양 타임 예약', '스냅 촬영', '플라워 데코'],
    tags: ['제주도', '석양', '해변'],
    price: '50만원~',
    styleTag: '야외 촬영',
    moodTag: '감성적',
    locationTag: '제주 해변',
    instagramUrl: 'https://www.instagram.com/wedu_jeju_sunset',
  },
  {
    id: 4,
    category: '💐 서비스',
    categoryType: '서비스',
    styles: ['로맨틱', '감성적'],
    tastes: ['꽃과 장미', '캔들 무드', '풍선 데코'],
    title: '프리미엄 플라워 데코',
    description: '수백 송이의 장미와 캔들로 연출하는 로맨틱 무대',
    detailDescription:
      '수백 송이의 생화 장미와 캔들을 활용해 로맨틱한 무대를 연출합니다. 원하는 공간에 맞춰 맞춤 데코레이션을 제공합니다.',
    includes: ['생화 장미 데코', '캔들 세팅', '현장 설치/철거', '맞춤 디자인'],
    tags: ['플라워', '데코', '장미'],
    price: '30만원~',
    styleTag: '생화 장미 데코',
    moodTag: '로맨틱',
    instagramUrl: 'https://www.instagram.com/wedu_flower_deco',
  },
  {
    id: 5,
    category: '📸 서비스',
    categoryType: '서비스',
    styles: ['감성적', '아늑한'],
    tastes: ['사진 촬영', '영상 편지'],
    title: '프로포즈 포토그래퍼',
    description: '눈물과 감동의 순간을 아름다운 화보로 남겨드립니다',
    detailDescription:
      '전문 포토그래퍼가 프로포즈의 모든 순간을 아름다운 화보로 담아드립니다. 스냅과 영상 촬영을 함께 제공합니다.',
    includes: ['스냅 촬영 2시간', '보정본 30장', '원본 전체 제공', '영상 클립'],
    tags: ['사진', '화보', '스냅'],
    price: '40만원~',
    styleTag: '스냅 촬영',
    moodTag: '감성적',
    instagramUrl: 'https://www.instagram.com/wedu_proposal_photo',
  },
  {
    id: 6,
    category: '🎻 경험',
    categoryType: '경험',
    styles: ['우아한', '감성적'],
    tastes: ['라이브 음악'],
    title: '현악 4중주 라이브',
    description: '프로포즈 순간에 맞춰 감미로운 현악기 선율이 흐릅니다',
    detailDescription:
      '전문 연주자들의 현악 4중주 라이브 공연입니다. 프로포즈 순간에 맞춰 원하는 곡을 연주해 드립니다.',
    includes: ['4인 연주팀', '곡 선곡 상담', '30분 공연', '음향 장비'],
    tags: ['현악', '라이브', '클래식'],
    price: '60만원~',
    styleTag: '라이브 연주',
    moodTag: '우아한',
    instagramUrl: 'https://www.instagram.com/wedu_string_quartet',
  },
  {
    id: 7,
    category: '🎆 경험',
    categoryType: '경험',
    styles: ['모험적', '깜짝'],
    tastes: ['자연 속에서'],
    title: '프라이빗 불꽃놀이',
    description: '밤하늘을 수놓는 불꽃과 함께 YES를 외치는 순간',
    detailDescription:
      '프라이빗 공간에서 진행되는 불꽃놀이 연출입니다. 안전 관리 인력과 함께 밤하늘을 수놓는 특별한 순간을 만들어 드립니다.',
    includes: ['불꽃 연출', '안전 관리 인력', '허가 대행', '현장 세팅'],
    tags: ['불꽃놀이', '야간', '스페셜'],
    price: '120만원~',
    styleTag: '불꽃 연출',
    moodTag: '드라마틱',
    locationTag: '야외 공간',
    instagramUrl: 'https://www.instagram.com/wedu_fireworks',
  },
  {
    id: 8,
    category: '💍 선물',
    categoryType: '선물',
    styles: ['우아한', '로맨틱'],
    tastes: ['럭셔리 패키지', '손편지'],
    title: '커스텀 프로포즈 링',
    description: '세상에 단 하나뿐인 맞춤 제작 프로포즈 반지',
    detailDescription:
      '세상에 하나뿐인 맞춤 제작 프로포즈 반지입니다. 디자인 상담부터 제작까지 전 과정을 함께합니다.',
    includes: ['디자인 상담', '맞춤 제작', '각인 서비스', '고급 케이스'],
    tags: ['반지', '커스텀', '주얼리'],
    price: '200만원~',
    styleTag: '맞춤 제작',
    moodTag: '럭셔리',
    instagramUrl: 'https://www.instagram.com/wedu_custom_ring',
  },
  {
    id: 9,
    category: '🌿 장소',
    categoryType: '장소',
    styles: ['로맨틱', '아늑한'],
    tastes: ['꽃과 장미', '자연 속에서'],
    title: '시크릿 가든 프로포즈',
    description: '도심 속 숨겨진 비밀 정원에서 꽃향기 가득한 로맨틱 무대',
    detailDescription:
      '도심 한복판, 아는 사람만 아는 프라이빗 정원에서 진행하는 프로포즈입니다. 계절 꽃으로 가득 채운 아치와 조명으로 은밀하면서도 로맨틱한 분위기를 연출합니다.',
    includes: ['정원 대관 2시간', '플라워 아치 데코', '조명 세팅', '스냅 촬영'],
    tags: ['가든', '플라워', '프라이빗'],
    price: '60만원~',
    styleTag: '가든 데코',
    moodTag: '로맨틱',
    locationTag: '도심 비밀정원',
    instagramUrl: 'https://www.instagram.com/wedu_secret_garden',
  },
  {
    id: 10,
    category: '🎬 장소',
    categoryType: '장소',
    styles: ['감성적', '아늑한'],
    tastes: ['영상 편지', '단둘이'],
    title: '프라이빗 시네마 프로포즈',
    description: '둘만의 영화관에서 직접 만든 영상과 함께 감동의 순간을',
    detailDescription:
      '단둘이 통째로 대관하는 프라이빗 상영관에서, 두 사람만의 추억 영상을 스크린으로 함께 보며 프로포즈하는 이벤트입니다. 영상 편집까지 함께 지원합니다.',
    includes: ['상영관 대관 1시간', '추억 영상 편집', '스낵 & 음료', '스냅 촬영'],
    tags: ['시네마', '영상', '프라이빗'],
    price: '45만원~',
    styleTag: '프라이빗 상영',
    moodTag: '감성적',
    locationTag: '프라이빗 영화관',
    instagramUrl: 'https://www.instagram.com/wedu_private_cinema',
  },
  {
    id: 11,
    category: '💄 서비스',
    categoryType: '서비스',
    styles: ['우아한', '화려한'],
    tastes: ['메이크업', '스타일링'],
    title: '프로포즈 메이크업 & 스타일링',
    description: '프로포즈 당일, 가장 아름다운 모습으로 빛날 수 있도록',
    detailDescription:
      '프로포즈 당일 가장 빛나는 모습을 위한 전문 메이크업 & 헤어 스타일링 서비스입니다. 컨셉 상담 후 원하는 장소로 출장도 가능합니다.',
    includes: ['메이크업 & 헤어', '컨셉 상담', '출장 서비스', '리터치 키트'],
    tags: ['메이크업', '헤어', '스타일링'],
    price: '25만원~',
    styleTag: '출장 메이크업',
    moodTag: '우아한',
    instagramUrl: 'https://www.instagram.com/wedu_makeup_styling',
  },
  {
    id: 12,
    category: '🚗 서비스',
    categoryType: '서비스',
    styles: ['럭셔리', '로맨틱'],
    tastes: ['럭셔리 패키지', '와인&샴페인'],
    title: '리무진 픽업 서비스',
    description: '프로포즈 장소까지의 이동마저 특별하게, 럭셔리 리무진과 함께',
    detailDescription:
      '프로포즈 장소까지 이동하는 순간부터 특별하게 만들어주는 리무진 픽업 서비스입니다. 차 안에서 즐기는 샴페인 한 잔으로 설렘을 더합니다.',
    includes: ['리무진 픽업/샌딩', '샴페인 서비스', '전담 기사', '차량 데코'],
    tags: ['리무진', '픽업', '샴페인'],
    price: '35만원~',
    styleTag: '리무진 픽업',
    moodTag: '럭셔리',
    instagramUrl: 'https://www.instagram.com/wedu_limousine',
  },
  {
    id: 13,
    category: '🚁 경험',
    categoryType: '경험',
    styles: ['모험적', '드라마틱'],
    tastes: ['자연 속에서', '깜짝 이벤트'],
    title: '헬리콥터 나이트 투어',
    description: '반짝이는 도시 야경 위를 날며 특별한 순간을 연출하세요',
    detailDescription:
      '도심의 야경을 한눈에 담을 수 있는 헬리콥터 투어입니다. 비행 중 특별한 순간을 연출할 수 있도록 전담 크루가 함께합니다.',
    includes: ['헬리콥터 탑승 20분', '전담 크루 동승', '기념 촬영', '탑승 전 브리핑'],
    tags: ['헬리콥터', '야경', '투어'],
    price: '250만원~',
    styleTag: '야간 비행 투어',
    moodTag: '드라마틱',
    locationTag: '도심 야경',
    instagramUrl: 'https://www.instagram.com/wedu_heli_night_tour',
  },
  {
    id: 14,
    category: '🍷 경험',
    categoryType: '경험',
    styles: ['우아한', '감성적'],
    tastes: ['와인&샴페인', '미식'],
    title: '와이너리 프라이빗 테이스팅',
    description: '전문 소믈리에와 함께하는 프라이빗 와인 테이스팅 후 깜짝 프로포즈',
    detailDescription:
      '전문 소믈리에가 진행하는 프라이빗 와인 테이스팅 클래스입니다. 마지막 잔을 비우는 순간에 맞춰 깜짝 프로포즈를 연출할 수 있습니다.',
    includes: ['소믈리에 테이스팅 클래스', '와인 4종', '치즈 플래터', '프로포즈 타이밍 연출'],
    tags: ['와인', '테이스팅', '소믈리에'],
    price: '40만원~',
    styleTag: '와인 테이스팅',
    moodTag: '우아한',
    instagramUrl: 'https://www.instagram.com/wedu_winery_tasting',
  },
  {
    id: 15,
    category: '⌚ 선물',
    categoryType: '선물',
    styles: ['모던', '심플'],
    tastes: ['시계', '커플'],
    title: '커플 커스텀 워치',
    description: '두 사람의 이니셜과 날짜가 각인된 특별한 커플 시계',
    detailDescription:
      '두 사람의 이니셜과 기념일을 각인한 커스텀 커플 시계입니다. 데일리로 착용하기 좋은 미니멀한 디자인으로 제작됩니다.',
    includes: ['커플 시계 세트', '각인 서비스', '전용 케이스', '평생 A/S'],
    tags: ['시계', '커플', '각인'],
    price: '80만원~',
    styleTag: '커스텀 각인',
    moodTag: '모던',
    instagramUrl: 'https://www.instagram.com/wedu_custom_watch',
  },
];