import type { Product } from '../Shop/shopData';

// 웨딩 견적 페이지 전용 mock 데이터. id는 프로포즈 편집샵 상품(1~8)과 겹치지 않게 101번대 사용.
// PM 확인: 이번 제출 범위에서는 UI만 구현 (실제 견적 계산/결제 로직 없음)
export const WEDDING_PRODUCTS: Product[] = [
  // 예식장 견적
  {
    id: 101,
    category: '🏛️ 예식장',
    categoryType: '웨딩',
    weddingCategory: '예식장',
    styles: ['클래식', '우아한'],
    tastes: ['도심', '접근성 좋음'],
    title: '더 그랜드 웨딩홀',
    description: '넓은 채플과 우아한 홀을 갖춘 도심 속 웨딩 명소',
    detailDescription:
      '서울 도심에 위치한 프리미엄 웨딩홀입니다. 최대 300명 수용 가능한 그랜드홀과 아늑한 채플을 함께 운영하며, 스드메 패키지 연계도 가능합니다.',
    includes: ['홀 대관 3시간', '기본 조명/음향', '신부 대기실', '주차 200대'],
    tags: ['웨딩홀', '도심', '대형홀'],
    price: '2,500만원~',
    styleTag: '그랜드홀',
    moodTag: '클래식',
    locationTag: '서울 도심',
    instagramUrl: 'https://www.instagram.com/wedu_grand_hall',
  },
  {
    id: 102,
    category: '🏛️ 예식장',
    categoryType: '웨딩',
    weddingCategory: '예식장',
    styles: ['모던', '심플'],
    tastes: ['채광 좋음', '스몰웨딩'],
    title: '라 루체 스몰웨딩홀',
    description: '자연광이 가득한 소규모 프라이빗 웨딩 전문홀',
    detailDescription:
      '통유리로 자연광이 가득 들어오는 스몰웨딩 전문 공간입니다. 50~80인 규모의 프라이빗한 예식에 최적화되어 있습니다.',
    includes: ['홀 대관 2시간', '플라워 데코 기본', '리허설 1회', '케이터링 연계'],
    tags: ['스몰웨딩', '자연광', '프라이빗'],
    price: '1,200만원~',
    styleTag: '스몰웨딩홀',
    moodTag: '모던',
    locationTag: '서울 근교',
    instagramUrl: 'https://www.instagram.com/wedu_laluce_hall',
  },
  {
    id: 103,
    category: '🏛️ 예식장',
    categoryType: '웨딩',
    weddingCategory: '예식장',
    styles: ['럭셔리', '전통'],
    tastes: ['한옥', '야외'],
    title: '한옥 정원 예식',
    description: '고즈넉한 한옥과 정원에서 올리는 특별한 전통 예식',
    detailDescription:
      '전통 한옥과 아름다운 정원을 갖춘 예식 공간입니다. 사계절 다른 정원의 모습과 함께 특별한 예식을 완성할 수 있습니다.',
    includes: ['정원 대관 4시간', '전통 혼례 소품', '우천 대비 실내홀', '한복 대여 연계'],
    tags: ['한옥', '전통', '야외예식'],
    price: '1,800만원~',
    styleTag: '한옥 정원',
    moodTag: '전통',
    locationTag: '경기 근교',
    instagramUrl: 'https://www.instagram.com/wedu_hanok_garden',
  },

  // 예물 견적
  {
    id: 104,
    category: '💍 예물',
    categoryType: '웨딩',
    weddingCategory: '예물',
    styles: ['클래식', '우아한'],
    tastes: ['다이아몬드', '커플링'],
    title: '이터널 다이아몬드 커플링',
    description: '평생 함께할 클래식 다이아몬드 커플링 세트',
    detailDescription:
      '고급 다이아몬드와 플래티넘 소재로 제작하는 클래식 커플링입니다. 각인 서비스와 평생 A/S가 포함됩니다.',
    includes: ['커플링 세트', '각인 서비스', '평생 A/S', '전용 케이스'],
    tags: ['다이아몬드', '커플링', '플래티넘'],
    price: '350만원~',
    styleTag: '다이아몬드 커플링',
    moodTag: '클래식',
    instagramUrl: 'https://www.instagram.com/wedu_eternal_ring',
  },
  {
    id: 105,
    category: '💍 예물',
    categoryType: '웨딩',
    weddingCategory: '예물',
    styles: ['모던', '심플'],
    tastes: ['시계', '주얼리 세트'],
    title: '커플 워치 & 주얼리 세트',
    description: '심플하고 모던한 디자인의 커플 시계 & 주얼리 세트',
    detailDescription:
      '미니멀한 디자인의 커플 시계와 목걸이, 팔찌 세트입니다. 일상에서도 부담 없이 착용 가능한 실용적인 예물을 제안합니다.',
    includes: ['커플 시계 세트', '목걸이 1쌍', '전용 박스', '각인 서비스'],
    tags: ['시계', '주얼리세트', '데일리'],
    price: '280만원~',
    styleTag: '커플 워치',
    moodTag: '모던',
    instagramUrl: 'https://www.instagram.com/wedu_watch_jewelry',
  },
  {
    id: 106,
    category: '💍 예물',
    categoryType: '웨딩',
    weddingCategory: '예물',
    styles: ['럭셔리', '화려한'],
    tastes: ['예단', '전통 예물'],
    title: '프리미엄 예단 세트',
    description: '양가 어른들께 드리는 정성 가득한 프리미엄 예단',
    detailDescription:
      '전통 방식을 따르는 프리미엄 예단 세트입니다. 함 준비부터 포장까지 전 과정을 컨설팅해 드립니다.',
    includes: ['예단 함 세트', '한복지 및 이불', '포장/배송', '예단 컨설팅'],
    tags: ['예단', '전통', '양가상견례'],
    price: '500만원~',
    styleTag: '예단 세트',
    moodTag: '럭셔리',
    instagramUrl: 'https://www.instagram.com/wedu_yedan_premium',
  },

  // 신혼여행 견적
  {
    id: 107,
    category: '✈️ 신혼여행',
    categoryType: '웨딩',
    weddingCategory: '신혼여행',
    styles: ['럭셔리', '휴양'],
    tastes: ['오버워터 빌라', '스노클링'],
    title: '몰디브 오버워터 빌라 7일',
    description: '에메랄드빛 바다 위 프라이빗 빌라에서 보내는 완벽한 휴양',
    detailDescription:
      '몰디브 프라이빗 아일랜드 리조트의 오버워터 빌라 패키지입니다. 왕복 항공, 전 일정 조식/석식, 스노클링 액티비티가 포함됩니다.',
    includes: ['왕복 항공권', '오버워터 빌라 6박', '조식/석식', '스노클링 1회'],
    tags: ['몰디브', '허니문', '오버워터빌라'],
    price: '900만원~',
    styleTag: '오버워터 빌라',
    moodTag: '휴양',
    locationTag: '몰디브',
    instagramUrl: 'https://www.instagram.com/wedu_maldives_honeymoon',
  },
  {
    id: 108,
    category: '✈️ 신혼여행',
    categoryType: '웨딩',
    weddingCategory: '신혼여행',
    styles: ['로맨틱', '유럽'],
    tastes: ['도시 여행', '미식'],
    title: '이탈리아 로맨틱 투어 9일',
    description: '로마, 피렌체, 베니스를 잇는 클래식 유럽 허니문',
    detailDescription:
      '로마-피렌체-베니스를 순환하는 이탈리아 클래식 코스입니다. 전용 가이드와 함께 미식 투어와 곤돌라 탑승이 포함됩니다.',
    includes: ['왕복 항공권', '4성급 호텔 8박', '전용 가이드', '곤돌라 탑승'],
    tags: ['이탈리아', '유럽', '허니문'],
    price: '850만원~',
    styleTag: '유럽 도시 투어',
    moodTag: '로맨틱',
    locationTag: '이탈리아',
    instagramUrl: 'https://www.instagram.com/wedu_italy_honeymoon',
  },
  {
    id: 109,
    category: '✈️ 신혼여행',
    categoryType: '웨딩',
    weddingCategory: '신혼여행',
    styles: ['모험적', '자연'],
    tastes: ['국립공원', '캠핑'],
    title: '뉴질랜드 자연 힐링 8일',
    description: '남섬의 대자연 속에서 즐기는 액티브 허니문',
    detailDescription:
      '뉴질랜드 남섬의 국립공원과 피오르드를 잇는 자연 힐링 코스입니다. 렌터카 자유여행 형태로, 원하는 액티비티를 자유롭게 추가할 수 있습니다.',
    includes: ['왕복 항공권', '렌터카 7일', '숙박 7박', '밀포드 사운드 크루즈'],
    tags: ['뉴질랜드', '자연', '액티브허니문'],
    price: '780만원~',
    styleTag: '자연 힐링 투어',
    moodTag: '모험적',
    locationTag: '뉴질랜드',
    instagramUrl: 'https://www.instagram.com/wedu_nz_honeymoon',
  },
];